fix: Remove gazelle_binary import collision
bazelbuild/bazel-gazelle pull request #1226
Opened 2022-04-04 13:11 UTC by illicitonion

**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

internal/gazelle_binary

**What does this PR do? Why is it needed?**

These changes make the import aliases for the generated Go code in gazelle_binary longer to avoid collisions.

Without theses changes, importing 2 gazelle extensions with the same base path would fail to build the gazelle binary:

```starlark
gazelle_binary(
    name = "gazelle_bin",
    languages = [
        # importpath = github.com/bazelbuild/bazel-skylib/gazelle
        "@bazel_skylib//gazelle/bzl",
        # importpath = github.com/bazelbuild/rules_python/gazelle
        "@rules_python//gazelle:gazelle_python_binary",
    ],
)
```

```console
$ bazel build //:gazelle_bin
[...  snip]
bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go:10:2: gazelle_ redeclared in this block
	bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go:9:2: other declaration of gazelle_
bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go:10:2: imported and not used: "github.com/bazelbuild/rules_python/gazelle" as gazelle_
```

The **current** generated bazel-out/darwin-fastbuild/bin/gazelle_bin_/langs.go file:

```go
package main

import (
	"github.com/bazelbuild/bazel-gazelle/language"

	gazelle_ "github.com/bazelbuild/bazel-skylib/gazelle"
	gazelle_ "github.com/bazelbuild/rules_python/gazelle"
)

var languages = []language.Language{
	gazelle_.NewLanguage(),
	gazelle_.NewLanguage(),
}
```

With the proposed changes, this file would become:

```go
package main

import (
	"github.com/bazelbuild/bazel-gazelle/language"

	github_com_bazelbuild_bazel_skylib_gazelle_ "github.com/bazelbuild/bazel-skylib/gazelle"
	github_com_bazelbuild_rules_python_gazelle_ "github.com/bazelbuild/rules_python/gazelle"
)

var languages = []language.Language{
	github_com_bazelbuild_bazel_skylib_gazelle_.NewLanguage(),
	github_com_bazelbuild_rules_python_gazelle_.NewLanguage(),
}
```

2022-04-04 20:09 UTC, achew22 commented
This seems like a good fix, but it's a smidge difficult to validate as just a code change. Is there any way you could add a [test case] for this?

You can create a new file `internal/gazelle_binary_test.bzl` with something like

```bzl
load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load(":gazelle_binary.bzl", format_import="_format_import", format_call="_format_call")

def _gazelle_binary_test_impl(ctx):
  env = unittest.begin(ctx)
  asserts.equals(env, "formatted_call", format_call("asdf"))
  asserts.equals(env, "formatted_import", format_import("asdf"))
  return unittest.end(env)

_gazelle_binary_test = unittest.make(_gazelle_binary_test_impl)

def gazelle_binary_test_suite(name):
  # unittest.suite() takes care of instantiating the testing rules and creating
  # a test_suite.
  unittest.suite(
    name,
    _gazelle_binary_test,
    # more tests if you want
  )
```

In `internal/BUILD.bazel` you can do:

```bzl
load(":gazelle_binary_test.bzl", "gazelle_binary_test_suite")

gazelle_binary_test_suite(name = "gazelle_binary_tests")
```


[test case]: https://bazel.build/rules/testing#testing-starlark-utilities

2022-04-04 20:09 UTC, achew22 requested changes
Oops, replied in the wrong place. See previous comment

2022-04-05 10:24 UTC, illicitonion commented
Done - do you know if there's a way to import private functions in tests?

I tried importing the private functions as you suggested in the example:

```starlark
load(":gazelle_binary.bzl", format_import="_format_import", format_call="_format_call")
```

But this does not work apparently:

```
ERROR: [snip]/internal/gazelle_binary_test.bzl:2:44: symbol '_format_call' is private and cannot be imported
ERROR: [snip]/internal/gazelle_binary_test.bzl:2:76: symbol '_format_import' is private and cannot be imported
```

If there is a way to import private functions, I would prefer it. If not I made the functions importable in these changes. I understand the files are in the internal directory already, so their "repo-local" nature is already encoded.

2022-04-05 20:36 UTC, achew22 approved these changes
I did a little sleuthing and I don't think that it's possible to do that. Fortunately, these functions live in `internal` so they are not importable to an external party, they would have to explicitly be imported and reexported by something outside that directory so I don't think the visibility of this is being significantly increased and I don't want to block `rules_python` being imported just because of this.

Thanks so much for your contribution!

2022-04-05 20:36 UTC, merged